### ISSUE TITLE
The boltdb error

### ISSUE THREAD

**Issue by sertoa812** [stucco/document-service#1]
On my vagrant environment , the doc-service have this error :

> Unable to create the metadata database data/doc.db: invalid argument.

and I trace back to the code and I found that this error was risen here:
`database, err := bolt.Open(f, 0600, &bolt.Options{Timeout: 1 * time.Second})
if err != nil {
		log.Fatalf("Unable to create the metadata database %s: %s", f, err)
	}`
which in the doc-service.go 153 line.

I tried some solutions , such as change the dataDir into empty and in anohter file , but it still make this error.
I wonder where is the problem.
Thanks a lot.

**Comment by jgoodall** [comment]
I am unable to replicate this. I increased the timeout to 5 sec and pushed, butI don't really think that is it. I think it is Vagrant-related. Is this a Windows host? Or a Mac? If so, this may be relevant:
https://github.com/boltdb/bolt/issues/272

Please let me know if you are able to get it to work.

**Comment by sertoa812** [comment]
I have got the problem solved.I think that the cause is similar to  [boltdb/bolt#272](https://github.com/boltdb/bolt/issues/272). It is just the shared folder problem.I git this repo in my /home folder instead of the shared folder and this make it worked.
But I am confused that I am using the host Linux instead of Windows. And the file system is all ext4. And I want to mention that I have two OS on my machine , the other is Windows.Is that make different?
Really appreciate for your time.

**Comment by jgoodall** [comment]
Great! Did you have to change the Vagrantfile at all?

**Comment by sertoa812** [comment]
I am sorry that i didn't notice your reply...
I didnt change the Vagrantfile, I only change the location of this repo.....
I am really sorry for that I didn't notice it....

**Comment by jgoodall** [comment]
No problem, glad it worked out.
